person:
  name: 张三
  age: 18
  birth-day: 2010/10/10 12:12:12
  like: true
  child:
    name: 李四
    age: 12
    birth-day: 2018/10/10
#    text:
#      - abc
#      - def
    text: ["abc","def"]
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 4
  cats:
    c1:
      name: 小兰
      age: 3
    c2: {name: 小黄, age: 2}